---
- name: Setup Ubuntu Server with UFW and other packages
  hosts: azure
  become: true
  tasks:
    
    - name: Update apt and install required system packages
      apt:
        name:
          - curl
          - vim
          - git
          - ufw
        state: latest
        update_cache: true

   
